coop_tilleuls_forgot_password:
    resource: "@CoopTilleulsForgotPasswordBundle/Resources/config/routing.xml"
    prefix: /forgot_password


coop_tilleuls_forgot_password.get_token:
    path: /forgot_password/{tokenValue}
    methods: [ GET ]
    defaults:
        _controller: App\Controller\GetTokenController